name: "CI Publish"

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

jobs:
  test-results:
    name: "CI Publish Followup"
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    runs-on: ubuntu-latest
    timeout-minutes: 1

    permissions:
      # dawidd6/action-download-artifact
      actions: read
      # EnricoMi/publish-unit-test-result-action
      checks: write

    steps:

      - name: "Download and Extract Artifacts"
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: "Publish 'Unit Results' check suite."
        if: ${{ success() || failure() }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/CI Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          check_name: '🔔 Test: Unit Results'
          comment_mode: off
          report_individual_runs: true
          test_changes_limit: 0
          action_fail_on_inconclusive: true
          junit_files: |
            **/build/test-results/*/TEST-*.xml
